version: '3'

services:
  deep_lab:
    build: ..
    container_name: "stock_deep_lab"
    working_dir: "/workspace"
    ports:
    - "6006:6006"
    - "8888:8888"
    volumes:
    - .:/workspace
    tty: true
